[pytx][hash_cmd] FileHasher instead BytesHasher in hash cli
facebook/ThreatExchange pull request #1077
Opened 2022-07-19 22:23 UTC by BarrettOlson

Summary
---------

If a signal type class extends `signal_base.FileHasher` the hash_cmd wouldn't recognize it because it was only looking for subclasses of `BytesHasher` (FileHasher is a parent of BytesHasher)

BytesHasher "is a" FileHasher so anything that inherits for BytesHasher is still supported by the change.

Test Plan
---------

`threatexchange hash --signal-type video_md5 video <video-file>` still works

and if you install something like `video_vpdq` (docs WIP) it will now also work

`threatexchange hash --signal-type video_vpdq video <video-file>`

2022-07-19 22:54 UTC, sahanapeters approved these changes
LGTM 👍

2022-07-20 02:31 UTC, tigerchensh commented
I think it you can fix by using hash_from_file from both TextHasher and ByteHasher while not checking any of their types.
```
hashers = [s for s in all_signal_types if issubclass(s, FileHasher)]
for file in self.files:
    for hasher in hashers:
        hash_str = s_hasher.hash_from_file(file)
        _print_hash(s_hasher, hash_str)
```
Because with each subclass, their hash_from_file is override and it utilizes the benefit of having the inheritance from FileHasher.

2022-07-20 02:33 UTC, tigerchensh requested changes
I think it you can fix by using hash_from_file from both TextHasher and ByteHasher while not checking any of their types.
```
hashers = [s for s in all_signal_types if issubclass(s, FileHasher)]
for file in self.files:
    for hasher in hashers:
        hash_str = hasher.hash_from_file(file)
        _print_hash(hasher, hash_str)
```
Because within each subclass, their hash_from_file is override and it utilizes the benefit of having the inheritance from FileHasher.

2022-07-20 14:39 UTC, BarrettOlson commented
Addressed in #1078

2022-07-20 14:39 UTC, closed without merging