stopncii submit_feedbacks will throw AttributeError
facebook/ThreatExchange pull request #1232
Opened 2022-12-09 18:18 UTC by Gnomeek

Summary
---------

Calling `StopNCII().submit_feedbacks()` will throw a `AttributeError` even though parameter is fine.
A unittest to catch this error is included in this PR.

Test Plan
---------

`StopNCII().submit_feedbacks()` should not raise error expect for `NetworkError`, etc.

2022-12-09 18:19 UTC, Gnomeek commented
Hey @dreiss , just find an issue in `StopNCII().submit_feedbacks()`. I have attached a reproducible unittest in this PR and will commit a patch to fix it.

2022-12-09 18:28 UTC, Gnomeek commented
the solution is quite straight-forward.

```python
@dataclass
class StopNCIICSPFeedback:
    """Feedback on a hash from a Content Service Provider"""

    feedbackValue: StopNCIICSPFeedbackValue  # What the feedback is
    tags: t.Set[str] = field(default_factory=set)  # Unstructured additional tags
    source: str = ""  # Name of the Content Service Provider (CSP)

    # --@classmethod
    # --def as_dict_for_post(cls) -> t.Dict[str, t.Any]:
    def as_dict_for_post(self) -> t.Dict[str, t.Any]:
        """The json-friendly format to send in post requests"""
        return {
            # --"tags": list(cls.tags),
            # --"feedbackValue": str(cls.feedbackValue),
            "tags": list(self.tags),
            "feedbackValue": str(self.feedbackValue),
        }
```

2022-12-09 18:32 UTC, Gnomeek commented
#1233 link issue for record

2022-12-09 21:09 UTC, Dcallies requested changes
Hey again @Gnomeek ! Thanks for the report. 

Since you have the repo, do you want to try your hand at the fix, or should I give a shot?

Simply re-request review if you would prefer to land as is and I'll take over.

2022-12-09 21:36 UTC, Gnomeek commented
> Hey again @Gnomeek ! Thanks for the report.
> 
> Since you have the repo, do you want to try your hand at the fix, or should I give a shot?
> 
> Simply re-request review if you would prefer to land as is and I'll take over.

yea, I can do that. Just wondering how to write proper unittests since `_post()` doesn't return anything, hence it's hard to do assertion.

2022-12-09 21:54 UTC, Gnomeek commented on python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
> +from dataclasses import dataclass, field
delete unused imports

2022-12-09 21:54 UTC, Gnomeek commented on python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
> +            "feedbackValue": self.feedbackValue.value,
`str(self.feedbackValue)` looks like `StopNCIICSPFeedbackValue.Blocked`, which should be `Blocked`, derived from `enum.value`

2022-12-09 21:54 UTC, Gnomeek commented on python-threatexchange/threatexchange/exchanges/clients/stopncii/tests/test_api.py
> +    assert json == desired_json
assert here since `submit_feedbacks` has no return value

2022-12-11 03:13 UTC, Dcallies commented
Hey @Gnomeek, it's always a challenge to test external APIs, since the API can change even if your unittests all still pass!

If you can fix the bug and your labels now show up in the NCII database in your test plan, I'd accept that even without a unittest.

For the lint errors, I've had that on the backburned to fix - this issue is we just need to fix it to a single version (the same one that HMA uses) - they passed at one point, but mypy has gotten better at detecting historical errors.

2022-12-11 03:16 UTC, Dcallies approved these changes
Thanks again for another fix! I'll roll a new version on Monday.

2022-12-11 03:16 UTC, Dcallies commented on python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
> -    def as_dict_for_post(cls) -> t.Dict[str, t.Any]:
Weird, I'm not sure why this was a classmethod before. Clearly I never tried to write a feedback with it (hence the bug)!

2022-12-11 03:17 UTC, merged