[RFC] Introducing DBM for storage
facebook/ThreatExchange pull request #1297
Opened 2023-03-29 15:32 UTC by NikolayOG

Summary
Draft commit, please focus on `DMBFetchedStateStore` class. 

Test Plan

1. Delete the pdq index
2. Run

```
threatexchange match photo https://github.com/facebook/ThreatExchange/blob/main/pdq/data/misc-images/b.jpg?raw=true
No data to match against
```

3. Run 
`threatexchange fetch`
4. Run
5. Run
```
threatexchange match photo https://github.com/facebook/ThreatExchange/blob/main/pdq/data/misc-images/b.jpg?raw=true
pdq 16 (Sample Signals) INVESTIGATION_SEED
```
Now we are finding matches

2023-03-29 15:35 UTC, NikolayOG commented on python-threatexchange/threatexchange/cli/cli_config.py
> +        return DMBFetchedStateStore(api)
Ignore this for now, 

Next steps would be to propagate storage flag from the cli terminal and select the correct storage interface class

2023-03-29 15:35 UTC, NikolayOG commented on python-threatexchange/threatexchange/exchanges/helpers.py
> +class DMBFetchedStateStore(fetch_state.FetchedStateStoreBase):
Please focus on this class, thanks!

2023-03-30 12:35 UTC, Dcallies reviewed
Awesome work!

Thanks for filling out a test plan.

Based on your work here, I think we can actually simplify the base interface to make it easier to implement as an extension. Catch me at the hackathon and we can talk through it!

2023-03-30 12:35 UTC, Dcallies commented on python-threatexchange/threatexchange/exchanges/helpers.py
> +class DMBFetchedStateStore(fetch_state.FetchedStateStoreBase):
DMB or DBM?

2023-03-30 12:35 UTC, Dcallies commented on python-threatexchange/threatexchange/exchanges/helpers.py
> +                    _k, _v = map(pickle.loads, [k, db[k]])
nit: underscores usually denote that the variable is unused (not that it's private as in other language conventions), so `k`, `v` is probably preferred.

2023-03-30 12:35 UTC, Dcallies commented on python-threatexchange/threatexchange/exchanges/helpers.py
> +    ) -> None:
All of these methods end up taking a collaboration implicitly, and we could probably provide a wrapper that could cover the equivalent of get_for_signal_type.

2023-04-02 02:16 UTC, Dcallies requested changes
Awesome progress! I think this is starting to narrow in on what I think will solve the GIFCT's issues and give us some flexibility in future designs.

Toplevel thoughts:
1. Let's continue iterating on the GenericStorage interface - this feel like it will play out in the long term more than specializing for the whole
2. Can you add some docstrings to the GenericStorage index? 
3. (Doesn't yet need to be solved / future PR) Consider also how it might be possible to port the old pickle + dict storage forward. We make a compatibility guarantee for users of the CLI

2023-04-02 02:16 UTC, Dcallies commented on python-threatexchange/threatexchange/exchanges/storage.py
> +    def exists(self, *args, **kwargs):
Having *args and **kwargs is probably overkill.

2023-04-02 02:16 UTC, Dcallies commented on python-threatexchange/threatexchange/exchanges/storage.py
> +    def connect(self, *args, **kwargs):
If we require that a constructing an instance of this object make it functional, do we need this method?

2024-03-01 18:23 UTC, Dcallies commented
Hey @NikolayOG, I'm going to close this PR for inactivity, feel free to re-open if you still want to try and get it merged!

2024-03-01 18:23 UTC, closed without merging