Modularise the Hasher code from the hasher CLI
facebook/ThreatExchange pull request #1303
Opened 2023-03-30 15:22 UTC by Sam-Freeman

Summary
---------

Pretty much as title, this is quite simple. It's the first iteration, and likely not the final form. 

Test Plan
---------

Ran locally, produces same result. All tests pass

2023-03-30 15:24 UTC, Sam-Freeman commented
Note: some of these were just merged in #1302 but are still showing up here.

2023-04-01 22:51 UTC, Dcallies requested changes
I like the general thrust of this, and I think we are unequivocally going to do something very similar to this in pulling out components for HMAiaB.

However, I'm not convinced at some of the top level choices on the interface yet:
1. I don't think passing in the settings object is needed for this functionality, and may be detrimental. 
2. Stepping back, what does a Hasher object represent? What would be the advantage over a functional version?
3. Which things might be details of the CLI, and which things might be generalized?
4. Looking at SignalType interface, we support 3 versions: bytes hasher, str hasher, and then a superclass - file hasher. How should that map to the hasher instance/helper?
5. Which version will HMAiaB need, assuming that it will be sent original content?
6. Is there anything we can learn from UnifiedHasher in AWS HMA? https://github.com/facebook/ThreatExchange/blob/main/hasher-matcher-actioner/hmalib/hashing/unified_hasher.py

2023-04-01 22:51 UTC, Dcallies commented on python-threatexchange/threatexchange/hasher/hasher.py
> +        settings: CLISettings,
It looks like the only thing you pass in the settings type for is the list of signal types. What if you passed in the full list of signal types? 

Alternatively, you only use content type to narrow down to the applicable signal types. What if you only passed in those?

2023-04-01 22:51 UTC, Dcallies commented on python-threatexchange/threatexchange/cli/hash_cmd.py
> +        hasher = Hasher(settings, self.content_type, self.signal_type)
blocking: Unfortunately, anything that is being passed in the settings god object is still heavily tied in with the CLI.

2024-03-01 18:24 UTC, Dcallies commented
Hey @Sam-Freeman , I'm going to close this PR for inactivity, feel free to re-open if you still want to try and get it merged!

2024-03-01 18:24 UTC, closed without merging