always mark sample test dataset id as in_use
facebook/ThreatExchange pull request #717
Opened 2021-07-14 19:58 UTC by mengyangwang

Summary
---------

This PR will not mark sample test dataset as in_active when users click "sync" button in ThreatExchange settings UI.

Test Plan
---------

1. black hmalib
2. mypy hmalib
3. python -m py.test to pass all tests
4. make docker
5. make upload_docker 
6. terraform apply
7. test in localhost

before : 

https://user-images.githubusercontent.com/81996660/125684911-1f9edc31-311d-489a-92fa-6e8129adb164.mov

after:

https://user-images.githubusercontent.com/81996660/125684940-1d4021af-be5a-4dd7-b9c1-cbc5cc12c3c6.mov

2021-07-14 20:45 UTC, BarrettOlson requested changes
This means syncing with TE will always add the sample privacy groups. I do not think we want this.

2021-07-14 20:49 UTC, BarrettOlson commented
if they haven't hit the 'Create' button my understanding is this will create it? Given that those sample hashes are likely to be something you'd want to action in productions, at a minimum I think this should default matching to off. Thoughts?

2021-07-14 20:57 UTC, mengyangwang commented
> if they haven't hit the 'Create' button my understanding is this will create it? Given that those sample hashes are likely to be something you'd want to action in productions, at a minimum I think this should default matching to off. Thoughts?

No It will not add the 

> if they haven't hit the 'Create' button my understanding is this will create it? Given that those sample hashes are likely to be something you'd want to action in productions, at a minimum I think this should default matching to off. Thoughts?

2021-07-14 21:00 UTC, mengyangwang commented
> if they haven't hit the 'Create' button my understanding is this will create it? Given that those sample hashes are likely to be something you'd want to action in productions, at a minimum I think this should default matching to off. Thoughts?

No it will not add sample dataset if they haven't hit the "create" button, I added a video to show this. Adding sample test id to priavcy_group_id_in_use set will just be used to compare with current datasets in dynamoDB, it will not create anything

2021-07-14 21:58 UTC, BarrettOlson approved these changes
My mistake, thanks for the additional test case. Maybe someday I'll get used to the way github compressed code, I thought this was in `create_privacy_group_if_not_exists` at first.

LGTM. Apologies (though having this be passed to `priavcy_group_id_in_use` for all cases does feel weird)

2021-07-19 15:38 UTC, schatten approved these changes
LGTM.

2021-07-27 17:34 UTC, merged