Filter Partner Bucket Uploads to files in specific folders or with specific extensions
facebook/ThreatExchange pull request #727
Opened 2021-07-23 16:48 UTC by jeberl

!!! This is a stacked PR. Only review 3e9bc1f "Add params to Partner Local Buckets terraform arg" !!!

Summary
---------

Partners who want to upload their banks to HMA will likely only want to send specific file types and specific folders within buckets to HMA. This PR enables this through prefix filtering and suffix filtering in terraform

Test Plan
---------

Ran the following tests by editing my tfvars file, running `terraform plan`, and looking at what would change in AWS as a result.

## Test 1
Change: `params:{"prefix" : "test/folder/path/"}`

Result:
```
## module.api.aws_s3_bucket_notification.bucket_notification[0] will be updated in-place
  ~ resource "aws_s3_bucket_notification" "bucket_notification" {
        id     = "jesses-separate-aws-bucket"
        # (1 unchanged attribute hidden)

      ~ lambda_function {
          + filter_prefix       = "test/folder/path/"
            id                  = "tf-s3-lambda-20210721194532010900000001"
            # (2 unchanged attributes hidden)
        }
    }
```

## Test 2 - Same result as Test 1
Change: `params:{"folder" : "test/folder/path/"}`

## Test 3 - Same result as Test 1
Change: `params:{"path" : "test/folder/path/"}`

## Test 4
Change: `params:{"suffix" : ".jpg"}`

Result:
```
## module.api.aws_s3_bucket_notification.bucket_notification[0] will be updated in-place
  ~ resource "aws_s3_bucket_notification" "bucket_notification" {
        id     = "jesses-separate-aws-bucket"
        # (1 unchanged attribute hidden)

      ~ lambda_function {
          + filter_suffix       = ".jpg"
            id                  = "tf-s3-lambda-20210721194532010900000001"
            # (2 unchanged attributes hidden)
        }
    }
```

## Test 5 - Same result as Test 4
Change: `params:{"extension" : ".jpg"}`

## Test 6
Change: `params:{"extension" : ".jpg", "folder" : "test/folder/path/"}`

Result:
```
## module.api.aws_s3_bucket_notification.bucket_notification[0] will be updated in-place
  ~ resource "aws_s3_bucket_notification" "bucket_notification" {
        id     = "jesses-separate-aws-bucket"
        # (1 unchanged attribute hidden)

      ~ lambda_function {
          + filter_suffix       = ".jpg"
          + filter_prefix       = "test/folder/path/"
            id                  = "tf-s3-lambda-20210721194532010900000001"
            # (2 unchanged attributes hidden)
        }
    }
```

## Test 7
Change: `params:{"not-a-key" : ".jpg", "folder" : "test/folder/path/"}`

Result:
```
Error: Invalid value for variable
│
│   on variables.tf line 91:
│   91: variable "partner_image_buckets" {
│
│ The only accepted params are 'prefix' to specify a prefix/folder/path string where only uploads with that prefix should be sent to HMA and 'extension' to restrict uploads to only files with a specific extension.
│
│ This was checked by the validation rule at variables.tf:101,3-13.
```

2021-07-27 19:37 UTC, Dcallies commented
Did any test involve uploading an image to that file and verifying it was processed by HMA?

What happens if the file name and prefix matches one that is in the original s3 bucket?

2021-07-27 19:44 UTC, jeberl commented
@Dcallies I didnt do an e2e test of prefix/suffix filtering. Only in #726 e2e tested image upload -> hasher

If you'd like an e2e test of prefix+suffix filtering I can do that

2021-07-27 20:01 UTC, Dcallies commented
It looks like the previous PR made it possible that you can have content id collisions if buckets and file names have overlaps

bucket/a b.jpg
bucket a/b.jpg
(original s3 bucket) bucket/a/b.jpg

Is there a way to handle this and guarantee content ids are unique? I think content ids being unique is an important property of the system.

2021-07-29 12:58 UTC, schatten requested changes
Can you clarify the reason for wanting a bag of variables in partner_image_buckets.params?

Otherwise, seems like a simple enough change.

2021-07-29 13:55 UTC, jeberl commented
> Can you clarify the reason for wanting a bag of variables in partner_image_buckets.params?

Terraform doesn't allow optional params so either you would have to specify `prefix=""` and `suffix=""` for no filtering. or `parms={}` which seemed easier

cc: @schatten

2021-07-29 20:46 UTC, schatten commented
> Terraform doesn't allow optional params within an object variable so either you would have to specify `prefix=""` and `suffix=""` for no filtering. or `parms={}` which seemed easier

It does allow defaults for parameters. A default of `prefix=""` and `suffix=""` would be no filtering which to me feels natural.

I guess this is subjective and a matter of taste, so I'll leave this for you to decide.

2021-07-29 20:46 UTC, schatten approved these changes

2021-07-30 13:39 UTC, jeberl commented
> It does allow defaults for parameters. A default of `prefix=""` and `suffix=""` would be no filtering which to me feels natural.

Discussed offline, within terraform entire variables can be optional, but individual parameters within object variables cannot

2021-07-30 13:39 UTC, merged