Index md5
facebook/ThreatExchange pull request #732
Opened 2021-07-27 19:50 UTC by schatten

Summary
---------

Test Plan
---------

2021-07-28 16:48 UTC, BarrettOlson commented on hasher-matcher-actioner/hmalib/common/s3_adapters.py
> +KNOWN_SIGNAL_TYPES: t.Type[SignalType] = [VideoMD5Signal, PdqSignal]
nit: why a module level const vs a static method of the `ThreatExchangeS3Adapter` class?

2021-07-28 16:50 UTC, BarrettOlson commented on hasher-matcher-actioner/hmalib/common/tests/test_s3_adapters.py
> +            store = ThreatUpdateS3Store(
nit: I like an overuse of keyword args in tests to I know what 'does-not-matter'

2021-07-28 16:55 UTC, BarrettOlson commented on hasher-matcher-actioner/hmalib/indexers/s3_indexers.py
> +- S3BackedPDQIndex: For distance matching of fixed width hashes like PDQ. Might
Note: TMK is not variable width just a lot larger than PDQ.

2021-07-28 17:07 UTC, BarrettOlson commented on hasher-matcher-actioner/hmalib/lambdas/unified_indexer.py
> +# signal_type. At some point, we must allow _updates_ to indexes rather than
irrc for FAISS the only 'efficient' update is a delete otherwise rebuild is just as fast in most cases.

2021-07-28 17:09 UTC, BarrettOlson commented on hasher-matcher-actioner/hmalib/lambdas/unified_indexer.py
> +        threat_exchange_pdq_file_extension="PHASE_OUT_THIS_INTERNAL_DETAIL",
?

2021-07-28 17:16 UTC, BarrettOlson commented on hasher-matcher-actioner/hmalib/lambdas/unified_indexer.py
> +_ADAPTER_MAPPING = {
it feels like we might want to have `s3_indexers.py` own this mapping instead... it feels like the file is half general and half not right now.

2021-07-28 17:21 UTC, BarrettOlson commented on hasher-matcher-actioner/terraform/indexer/main.tf
> +resource "null_resource" "provide_sample_pdq_data_holidays" {
nit: this isn't really part of the indexer so it might have a better place to live than this.

2021-07-28 17:22 UTC, BarrettOlson commented on hasher-matcher-actioner/terraform/pdq-signals/main.tf
> -# PDQ Indexer
remove the python source code as well?

2021-07-28 17:28 UTC, BarrettOlson requested changes
Generally makes sense. RC-ing mostly for questions and to request an e2e test like a storm be added to the test plan for this to make sure PDQ matching still works. 
Fine to stamp with a follow up like: "I tested this end2end and will consider the other changes while adding matching :)"

Thanks!
Commit reviews (added one off comments inline along the way): 
https://github.com/facebook/ThreatExchange/pull/732/commits/8ef9a7b069c6d3e1601ca0a782f46942723eee69 : LGTM (w/nits)

https://github.com/facebook/ThreatExchange/pull/732/commits/e501b14f05d7f149eeab8ca40ab09bacd91716b2 : Seems reasonable but confused on why you are using a mixin and not a parent class. Also doc string of `_get_index_s3_key` feels like more of a PR comment. I'd recommend either attaching your gh name and/or writing in past tense. 

https://github.com/facebook/ThreatExchange/pull/732/commits/5f603799072eba17574f2d22da9737039d1407ef : Generally fine (lot of different ways to tackle this) but ~hard to review. Ended up realizing I should compare to [pdq_indexer](https://github.com/facebook/ThreatExchange/blob/master/hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_indexer.py) to see the actual changes and the delta was relatively small.  This also ~explains the use of a mixin from the previous commit but I'm still not fully convinced (add reasoning to doc string of Mixin class?)


https://github.com/facebook/ThreatExchange/pull/732/commits/67bc6ae4d98e96356d7bf37d8817cab472d29464 : Okay but let’s clean up the python source code as well though.

2021-08-15 16:49 UTC, schatten commented
Merged as part of integration branch #749

2021-08-15 16:49 UTC, closed without merging